/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppReceitasRouteImport } from './routes/app.receitas'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMateriaisRouteImport } from './routes/app.materiais'
import { Route as AppEbooksRouteImport } from './routes/app.ebooks'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppCertificadosRouteImport } from './routes/app.certificados'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppEbooksIndexRouteImport } from './routes/app.ebooks.index'
import { Route as AppCursosIndexRouteImport } from './routes/app.cursos.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppEbooksEbookIdRouteImport } from './routes/app.ebooks.$ebookId'
import { Route as AppCursosPreviewRouteImport } from './routes/app.cursos.preview'
import { Route as AppCursosCourseIdRouteImport } from './routes/app.cursos.$courseId'
import { Route as AppAdminIntegracoesRouteImport } from './routes/app.admin.integracoes'
import { Route as AppAdminFinanceiroRouteImport } from './routes/app.admin.financeiro'
import { Route as AppAdminEbookAiRouteImport } from './routes/app.admin.ebook-ai'
import { Route as AppAdminAlunosRouteImport } from './routes/app.admin.alunos'
import { Route as AppEbooksPremiumEbookIdRouteImport } from './routes/app.ebooks.premium.$ebookId'
import { Route as AppEbooksGeradoIdRouteImport } from './routes/app.ebooks.gerado.$id'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisRoute = AppMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppEbooksRoute = AppEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificadosRoute = AppCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppEbooksIndexRoute = AppEbooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEbooksRoute,
} as any)
const AppCursosIndexRoute = AppCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppEbooksEbookIdRoute = AppEbooksEbookIdRouteImport.update({
  id: '/$ebookId',
  path: '/$ebookId',
  getParentRoute: () => AppEbooksRoute,
} as any)
const AppCursosPreviewRoute = AppCursosPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppCursosCourseIdRoute = AppCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAdminIntegracoesRoute = AppAdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFinanceiroRoute = AppAdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEbookAiRoute = AppAdminEbookAiRouteImport.update({
  id: '/ebook-ai',
  path: '/ebook-ai',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlunosRoute = AppAdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppEbooksPremiumEbookIdRoute = AppEbooksPremiumEbookIdRouteImport.update({
  id: '/premium/$ebookId',
  path: '/premium/$ebookId',
  getParentRoute: () => AppEbooksRoute,
} as any)
const AppEbooksGeradoIdRoute = AppEbooksGeradoIdRouteImport.update({
  id: '/gerado/$id',
  path: '/gerado/$id',
  getParentRoute: () => AppEbooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/ebooks': typeof AppEbooksRouteWithChildren
  '/app/materiais': typeof AppMateriaisRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/alunos': typeof AppAdminAlunosRoute
  '/app/admin/ebook-ai': typeof AppAdminEbookAiRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/app/ebooks/': typeof AppEbooksIndexRoute
  '/app/ebooks/gerado/$id': typeof AppEbooksGeradoIdRoute
  '/app/ebooks/premium/$ebookId': typeof AppEbooksPremiumEbookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/certificados': typeof AppCertificadosRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app': typeof AppIndexRoute
  '/app/admin/alunos': typeof AppAdminAlunosRoute
  '/app/admin/ebook-ai': typeof AppAdminEbookAiRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/cursos': typeof AppCursosIndexRoute
  '/app/ebooks': typeof AppEbooksIndexRoute
  '/app/ebooks/gerado/$id': typeof AppEbooksGeradoIdRoute
  '/app/ebooks/premium/$ebookId': typeof AppEbooksPremiumEbookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/ebooks': typeof AppEbooksRouteWithChildren
  '/app/materiais': typeof AppMateriaisRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/alunos': typeof AppAdminAlunosRoute
  '/app/admin/ebook-ai': typeof AppAdminEbookAiRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/app/ebooks/': typeof AppEbooksIndexRoute
  '/app/ebooks/gerado/$id': typeof AppEbooksGeradoIdRoute
  '/app/ebooks/premium/$ebookId': typeof AppEbooksPremiumEbookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/app/admin'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/ebooks'
    | '/app/materiais'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/app/'
    | '/app/admin/alunos'
    | '/app/admin/ebook-ai'
    | '/app/admin/financeiro'
    | '/app/admin/integracoes'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/admin/'
    | '/app/cursos/'
    | '/app/ebooks/'
    | '/app/ebooks/gerado/$id'
    | '/app/ebooks/premium/$ebookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/app/certificados'
    | '/app/materiais'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/app'
    | '/app/admin/alunos'
    | '/app/admin/ebook-ai'
    | '/app/admin/financeiro'
    | '/app/admin/integracoes'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/admin'
    | '/app/cursos'
    | '/app/ebooks'
    | '/app/ebooks/gerado/$id'
    | '/app/ebooks/premium/$ebookId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/app/admin'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/ebooks'
    | '/app/materiais'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/app/'
    | '/app/admin/alunos'
    | '/app/admin/ebook-ai'
    | '/app/admin/financeiro'
    | '/app/admin/integracoes'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/admin/'
    | '/app/cursos/'
    | '/app/ebooks/'
    | '/app/ebooks/gerado/$id'
    | '/app/ebooks/premium/$ebookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receitas': {
      id: '/app/receitas'
      path: '/receitas'
      fullPath: '/app/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materiais': {
      id: '/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AppMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ebooks': {
      id: '/app/ebooks'
      path: '/ebooks'
      fullPath: '/app/ebooks'
      preLoaderRoute: typeof AppEbooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificados': {
      id: '/app/certificados'
      path: '/certificados'
      fullPath: '/app/certificados'
      preLoaderRoute: typeof AppCertificadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ebooks/': {
      id: '/app/ebooks/'
      path: '/'
      fullPath: '/app/ebooks/'
      preLoaderRoute: typeof AppEbooksIndexRouteImport
      parentRoute: typeof AppEbooksRoute
    }
    '/app/cursos/': {
      id: '/app/cursos/'
      path: '/'
      fullPath: '/app/cursos/'
      preLoaderRoute: typeof AppCursosIndexRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/ebooks/$ebookId': {
      id: '/app/ebooks/$ebookId'
      path: '/$ebookId'
      fullPath: '/app/ebooks/$ebookId'
      preLoaderRoute: typeof AppEbooksEbookIdRouteImport
      parentRoute: typeof AppEbooksRoute
    }
    '/app/cursos/preview': {
      id: '/app/cursos/preview'
      path: '/preview'
      fullPath: '/app/cursos/preview'
      preLoaderRoute: typeof AppCursosPreviewRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/cursos/$courseId': {
      id: '/app/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/app/cursos/$courseId'
      preLoaderRoute: typeof AppCursosCourseIdRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/admin/integracoes': {
      id: '/app/admin/integracoes'
      path: '/integracoes'
      fullPath: '/app/admin/integracoes'
      preLoaderRoute: typeof AppAdminIntegracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/financeiro': {
      id: '/app/admin/financeiro'
      path: '/financeiro'
      fullPath: '/app/admin/financeiro'
      preLoaderRoute: typeof AppAdminFinanceiroRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ebook-ai': {
      id: '/app/admin/ebook-ai'
      path: '/ebook-ai'
      fullPath: '/app/admin/ebook-ai'
      preLoaderRoute: typeof AppAdminEbookAiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/alunos': {
      id: '/app/admin/alunos'
      path: '/alunos'
      fullPath: '/app/admin/alunos'
      preLoaderRoute: typeof AppAdminAlunosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/ebooks/premium/$ebookId': {
      id: '/app/ebooks/premium/$ebookId'
      path: '/premium/$ebookId'
      fullPath: '/app/ebooks/premium/$ebookId'
      preLoaderRoute: typeof AppEbooksPremiumEbookIdRouteImport
      parentRoute: typeof AppEbooksRoute
    }
    '/app/ebooks/gerado/$id': {
      id: '/app/ebooks/gerado/$id'
      path: '/gerado/$id'
      fullPath: '/app/ebooks/gerado/$id'
      preLoaderRoute: typeof AppEbooksGeradoIdRouteImport
      parentRoute: typeof AppEbooksRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAlunosRoute: typeof AppAdminAlunosRoute
  AppAdminEbookAiRoute: typeof AppAdminEbookAiRoute
  AppAdminFinanceiroRoute: typeof AppAdminFinanceiroRoute
  AppAdminIntegracoesRoute: typeof AppAdminIntegracoesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAlunosRoute: AppAdminAlunosRoute,
  AppAdminEbookAiRoute: AppAdminEbookAiRoute,
  AppAdminFinanceiroRoute: AppAdminFinanceiroRoute,
  AppAdminIntegracoesRoute: AppAdminIntegracoesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCursosRouteChildren {
  AppCursosCourseIdRoute: typeof AppCursosCourseIdRoute
  AppCursosPreviewRoute: typeof AppCursosPreviewRoute
  AppCursosIndexRoute: typeof AppCursosIndexRoute
}

const AppCursosRouteChildren: AppCursosRouteChildren = {
  AppCursosCourseIdRoute: AppCursosCourseIdRoute,
  AppCursosPreviewRoute: AppCursosPreviewRoute,
  AppCursosIndexRoute: AppCursosIndexRoute,
}

const AppCursosRouteWithChildren = AppCursosRoute._addFileChildren(
  AppCursosRouteChildren,
)

interface AppEbooksRouteChildren {
  AppEbooksEbookIdRoute: typeof AppEbooksEbookIdRoute
  AppEbooksIndexRoute: typeof AppEbooksIndexRoute
  AppEbooksGeradoIdRoute: typeof AppEbooksGeradoIdRoute
  AppEbooksPremiumEbookIdRoute: typeof AppEbooksPremiumEbookIdRoute
}

const AppEbooksRouteChildren: AppEbooksRouteChildren = {
  AppEbooksEbookIdRoute: AppEbooksEbookIdRoute,
  AppEbooksIndexRoute: AppEbooksIndexRoute,
  AppEbooksGeradoIdRoute: AppEbooksGeradoIdRoute,
  AppEbooksPremiumEbookIdRoute: AppEbooksPremiumEbookIdRoute,
}

const AppEbooksRouteWithChildren = AppEbooksRoute._addFileChildren(
  AppEbooksRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCertificadosRoute: typeof AppCertificadosRoute
  AppCursosRoute: typeof AppCursosRouteWithChildren
  AppEbooksRoute: typeof AppEbooksRouteWithChildren
  AppMateriaisRoute: typeof AppMateriaisRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCertificadosRoute: AppCertificadosRoute,
  AppCursosRoute: AppCursosRouteWithChildren,
  AppEbooksRoute: AppEbooksRouteWithChildren,
  AppMateriaisRoute: AppMateriaisRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
