/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppReceitasRouteImport } from './routes/app.receitas'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMateriaisRouteImport } from './routes/app.materiais'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppCertificadosRouteImport } from './routes/app.certificados'
import { Route as AppAfiliadosRouteImport } from './routes/app.afiliados'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminReceitasRouteImport } from './routes/admin.receitas'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminAoVivoRouteImport } from './routes/admin.ao-vivo'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAfiliadosRouteImport } from './routes/admin.afiliados'
import { Route as AppCursosIndexRouteImport } from './routes/app.cursos.index'
import { Route as AppAfiliadosIndexRouteImport } from './routes/app.afiliados.index'
import { Route as AppCursosPreviewRouteImport } from './routes/app.cursos.preview'
import { Route as AppCursosCourseIdRouteImport } from './routes/app.cursos.$courseId'
import { Route as AppAfiliadosLinksRouteImport } from './routes/app.afiliados.links'
import { Route as AppAfiliadosFinanceiroRouteImport } from './routes/app.afiliados.financeiro'
import { Route as AppAfiliadosConfigRouteImport } from './routes/app.afiliados.config'
import { Route as AdminAlunosStudentIdRouteImport } from './routes/admin.alunos.$studentId'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisRoute = AppMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificadosRoute = AppCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitasRoute = AdminReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAoVivoRoute = AdminAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const AppCursosIndexRoute = AppCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAfiliadosIndexRoute = AppAfiliadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppCursosPreviewRoute = AppCursosPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppCursosCourseIdRoute = AppCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAfiliadosLinksRoute = AppAfiliadosLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosFinanceiroRoute = AppAfiliadosFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosConfigRoute = AppAfiliadosConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AdminAlunosStudentIdRoute = AdminAlunosStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AdminAlunosRoute,
} as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/afiliados': typeof AppAfiliadosRouteWithChildren
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/afiliados/': typeof AppAfiliadosIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/certificados': typeof AppCertificadosRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/afiliados': typeof AppAfiliadosIndexRoute
  '/app/cursos': typeof AppCursosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/afiliados': typeof AppAfiliadosRouteWithChildren
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/afiliados/': typeof AppAfiliadosIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/receitas'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/admin'
    | '/app/afiliados'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/admin/alunos/$studentId'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/afiliados/'
    | '/app/cursos/'
    | '/api/public/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/receitas'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/admin'
    | '/app/certificados'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/admin'
    | '/app'
    | '/admin/alunos/$studentId'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/afiliados'
    | '/app/cursos'
    | '/api/public/webhooks/asaas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/receitas'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/admin'
    | '/app/afiliados'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/admin/alunos/$studentId'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/afiliados/'
    | '/app/cursos/'
    | '/api/public/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receitas': {
      id: '/app/receitas'
      path: '/receitas'
      fullPath: '/app/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materiais': {
      id: '/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AppMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificados': {
      id: '/app/certificados'
      path: '/certificados'
      fullPath: '/app/certificados'
      preLoaderRoute: typeof AppCertificadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/afiliados': {
      id: '/app/afiliados'
      path: '/afiliados'
      fullPath: '/app/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receitas': {
      id: '/admin/receitas'
      path: '/receitas'
      fullPath: '/admin/receitas'
      preLoaderRoute: typeof AdminReceitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ao-vivo': {
      id: '/admin/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/admin/ao-vivo'
      preLoaderRoute: typeof AdminAoVivoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/cursos/': {
      id: '/app/cursos/'
      path: '/'
      fullPath: '/app/cursos/'
      preLoaderRoute: typeof AppCursosIndexRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/afiliados/': {
      id: '/app/afiliados/'
      path: '/'
      fullPath: '/app/afiliados/'
      preLoaderRoute: typeof AppAfiliadosIndexRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/cursos/preview': {
      id: '/app/cursos/preview'
      path: '/preview'
      fullPath: '/app/cursos/preview'
      preLoaderRoute: typeof AppCursosPreviewRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/cursos/$courseId': {
      id: '/app/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/app/cursos/$courseId'
      preLoaderRoute: typeof AppCursosCourseIdRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/afiliados/links': {
      id: '/app/afiliados/links'
      path: '/links'
      fullPath: '/app/afiliados/links'
      preLoaderRoute: typeof AppAfiliadosLinksRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/financeiro': {
      id: '/app/afiliados/financeiro'
      path: '/financeiro'
      fullPath: '/app/afiliados/financeiro'
      preLoaderRoute: typeof AppAfiliadosFinanceiroRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/config': {
      id: '/app/afiliados/config'
      path: '/config'
      fullPath: '/app/afiliados/config'
      preLoaderRoute: typeof AppAfiliadosConfigRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/admin/alunos/$studentId': {
      id: '/admin/alunos/$studentId'
      path: '/$studentId'
      fullPath: '/admin/alunos/$studentId'
      preLoaderRoute: typeof AdminAlunosStudentIdRouteImport
      parentRoute: typeof AdminAlunosRoute
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAlunosRouteChildren {
  AdminAlunosStudentIdRoute: typeof AdminAlunosStudentIdRoute
}

const AdminAlunosRouteChildren: AdminAlunosRouteChildren = {
  AdminAlunosStudentIdRoute: AdminAlunosStudentIdRoute,
}

const AdminAlunosRouteWithChildren = AdminAlunosRoute._addFileChildren(
  AdminAlunosRouteChildren,
)

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminAlunosRoute: typeof AdminAlunosRouteWithChildren
  AdminAoVivoRoute: typeof AdminAoVivoRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminReceitasRoute: typeof AdminReceitasRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminAlunosRoute: AdminAlunosRouteWithChildren,
  AdminAoVivoRoute: AdminAoVivoRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminReceitasRoute: AdminReceitasRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAfiliadosRouteChildren {
  AppAfiliadosConfigRoute: typeof AppAfiliadosConfigRoute
  AppAfiliadosFinanceiroRoute: typeof AppAfiliadosFinanceiroRoute
  AppAfiliadosLinksRoute: typeof AppAfiliadosLinksRoute
  AppAfiliadosIndexRoute: typeof AppAfiliadosIndexRoute
}

const AppAfiliadosRouteChildren: AppAfiliadosRouteChildren = {
  AppAfiliadosConfigRoute: AppAfiliadosConfigRoute,
  AppAfiliadosFinanceiroRoute: AppAfiliadosFinanceiroRoute,
  AppAfiliadosLinksRoute: AppAfiliadosLinksRoute,
  AppAfiliadosIndexRoute: AppAfiliadosIndexRoute,
}

const AppAfiliadosRouteWithChildren = AppAfiliadosRoute._addFileChildren(
  AppAfiliadosRouteChildren,
)

interface AppCursosRouteChildren {
  AppCursosCourseIdRoute: typeof AppCursosCourseIdRoute
  AppCursosPreviewRoute: typeof AppCursosPreviewRoute
  AppCursosIndexRoute: typeof AppCursosIndexRoute
}

const AppCursosRouteChildren: AppCursosRouteChildren = {
  AppCursosCourseIdRoute: AppCursosCourseIdRoute,
  AppCursosPreviewRoute: AppCursosPreviewRoute,
  AppCursosIndexRoute: AppCursosIndexRoute,
}

const AppCursosRouteWithChildren = AppCursosRoute._addFileChildren(
  AppCursosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAfiliadosRoute: typeof AppAfiliadosRouteWithChildren
  AppCertificadosRoute: typeof AppCertificadosRoute
  AppCursosRoute: typeof AppCursosRouteWithChildren
  AppMateriaisRoute: typeof AppMateriaisRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAfiliadosRoute: AppAfiliadosRouteWithChildren,
  AppCertificadosRoute: AppCertificadosRoute,
  AppCursosRoute: AppCursosRouteWithChildren,
  AppMateriaisRoute: AppMateriaisRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
