
-- Ensure the bucket exists (idempotent via migration tool is tricky for buckets, 
-- but we know course-assets exists from read_query).

-- Policy to allow authenticated users to SELECT (read) objects from course-assets
-- only if they are matriculated/enrolled in the course/ebook associated?
-- For simplicity and following the project pattern, we'll allow authenticated reads
-- if they have a valid session, or we rely on Signed URLs generated by service_role.

-- Allow authenticated users to see the objects (required for getPublicUrl/list, though we use Signed URL)
CREATE POLICY "Allow authenticated users to read course assets"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'course-assets');

-- Ensure service_role has full access (usually default but being explicit)
CREATE POLICY "Allow service_role full access to course assets"
ON storage.objects FOR ALL
TO service_role
USING (bucket_id = 'course-assets')
WITH CHECK (bucket_id = 'course-assets');
